### ISSUE TITLE
Unclear ReadMe File

### ISSUE THREAD

**Issue by barakman** [snyk/nodejs-runtime-agent#100]
### Quick start
`require('@snyk/nodejs-runtime-agent')({ projectId: <Your-Project-ID> });`
### How to
`require('@snyk/nodejs-runtime-agent')(config);`

---

So... what exactly is the reader supposed to conclude from that?

In what JS file should this `require` statement be placed?

How exactly would this JS file be executed?
Presumably, by adding it as a post-install script in `package.json`.
But it is not explicitly mentioned anywhere, so did you intend for this to be carried out in a different manner?

Moreover, how exactly would that `require` statement work without adding a proper dependency in `package.json`?

I'm just saying, because:
1. Your [`npm` webpage](https://www.npmjs.com/package/@snyk/nodejs-runtime-agent) does not explain how to do that (and `"@snyk/nodejs-runtime-agent": "1.46.0"` is simply an illegal syntax in `package.json`)
2. Your [`installing-the-snyk-runtime-agent-for-node-js` instructions](https://snyk.io/docs/installing-the-snyk-runtime-agent-for-node-js/#installing-the-snyk-agent) do not clarify this in any way whatsoever

Thanks

**Comment by shaimendel** [comment]
Hi @barakman, thanks for reaching out!

the full documentation can be found at https://snyk.io/docs/runtime-protection/, and for node specifically at https://snyk.io/docs/installing-the-snyk-runtime-agent-for-node-js/.
we are here for any further questions.

Thanks
