### ISSUE TITLE
`npm run snyk-protect` is executed even with `"snyk": false`

### ISSUE THREAD

**Issue by barakman** [snyk/nodejs-runtime-agent#101]
My `package.json` file:
```
  "scripts": {
    "snyk-protect": "snyk protect",
    "prepare": "npm run snyk-protect"
  },
  "dependencies": {
    "snyk": "^1.208.0"
  },
  "snyk": false
```

### Expected behaviour

Executing `npm install` should end without `npm run snyk-protect`.

### Actual behaviour

Executing `npm install` ends with `npm run snyk-protect`.

**Comment by shaimendel** [comment]
please reopen this https://github.com/snyk/snyk if this is still relevant, thank you :)
